### PR TITLE
#144 | Launcher's key mapping option does not work.

### LINKED ISSUE #144: Launcher's key mapping option does not work.
I changed the key mapping of "Show Launcher" like the following, but it didn't work. I tried with other keycodes, but the results were the same.

launcher_key_mappings

### Steps to Reproduce the Problem
  1. Open the options page of the Launcher module.
  1. Set `81` to "Show Launcher".
  1. Press Ctrl + q on Sitecore.

### Expected Behavior
The launcher should be showed.

### Actual Behavior
The launcher does not show up.

### Specifications
Sitecore version: 9.2

### PR DESCRIPTION
**Pull request by xirtardauq**
Issue Fixed #144

### CODE REVIEW

**Comment by xirtardauq** [comment]
Sorry, it turns out that there is a problem with this fix. When built and used in developer mode, the following error was printed.

> Formly Error: There is no type by the name of "number".

#144 is caused by the fact that the keycode entered in the Keymapping form is treated as a string and the comparison with the number is always false: 

- LauncherModule.ts : L107

````javascript
registerGlobalShortcuts(): void {
    document.onkeydown = (evt: KeyboardEvent) => {
        evt = (evt ! = null ? evt : <KeyboardEvent>window.event);
        switch (evt.which || evt.keyCode) { // "evt.keyCode" has a number value.
            case this.options.keyBindings.show: { // But "show" property contains a string value.
                if (evt.ctrlKey) {
                    this.showLauncher();
                    break;
                }
                return;
            }
            case this.options.keyBindings.hide: { // And it's the same here.
                if (evt.target == this.searchBoxElement) {
                    this.hideLauncher();
                }
                break;
            }
            default: return;
        }
        evt.preventDefault();
    };
}
````

I would appreciate it if you could close for now this pull request,  or advise me on how to fix it.

Thank you.

**Comment by alan-null** [comment]
Solved here: https://github.com/alan-null/sc_ext/commit/76e721e9b6a7d10bf5906f823cba5be58985fb4e

**Comment by jflheureux** [comment]
Was a release made since this last fix? I had the same issue today. When exporting my settings, I saw that the keycode I had entered was a string instead of a number. I had to remove the quotes, save, and import the setting file to make it work as expected.

**Comment by alan-null** [comment]
@jflheureux unfortunately no.

last release:
image

good that there is a workaround.

**Pull request closed without merging**
